enable: true
users:
  default:  # 默认配置
    plugins:
      test:
        enable: true
        commands:
          "*": true  # 通配符表示所有命令默认允许
          
  # 用户/群组特定配置（可选）
  211249983:
    plugins:
      test:
        commands:
          dangerousCommand: false
          
  1008611:
    plugins:
      test:
        enable: true
        commands:
          MyCommand: true
          MyCommand2: false