enable: true
users:
  default:
    plugins:
      test:
        enable: true
        commands:
          help: true
          param: false
  '211249983':
    plugins:
      test:
        enable: true
        commands:
          help: true
          param: false
