enable: true
admins:
  - '2180323481'
  - '1814872986'
users:
  '211249983':
    plugins:
      test:
        enable: true
        commands:
          help: true
          param: true
      testupload:
        commands:
          help: true
          param: true
      downloadPlugins:
        commands:
          download: true
          help: true
          plugins: true
          logs: true
          downloadlog: true
      saku:
        commands:
          ping: true
          help: true
          图: true
      sakulass:
        commands:
          图: true
          help: true
      PluginsFile:
        commands:
          help: true
          logs: true
          downloadlog: true
  '914085636':
    plugins:
      saku:
        commands:
          help: true
      reload:
        commands:
          help: true
      downloadPlugins:
        commands:
          help: true
          plugins: true
          download: true
          logs: true
          downloadlog: true
      sakulass:
        commands:
          help: true
          图: true
  '1051027747':
    plugins:
      sakulass:
        commands:
          图: true
          一言: true
          help: true
      ecomony:
        commands:
          info: true
          add: true
          help: true
      test:
        commands:
          remove: true
          help: true
          param: true
      Botlog:
        commands:
          logs: true
          downloadlog: true
      Prop:
        commands:
          list: true
          help: true
          buy: true
          use: true
          my: true
  default:
    plugins:
      test:
        enable: true
        commands:
          help: true
          param: false
