enable: true
admins:
  - '2180323481'
  - '1814872986'
users:
  '211249983':
    plugins:
      test:
        enable: true
        commands:
          help: true
          param: true
      testupload:
        commands:
          help: true
          param: true
      downloadPlugins:
        commands:
          download: true
          help: true
          plugins: true
          logs: true
          downloadlog: true
      saku:
        commands:
          ping: true
          help: true
          图: true
      sakulass:
        commands:
          图: true
          help: true
      PluginsFile:
        commands:
          help: true
  '914085636':
    plugins:
      saku:
        commands:
          help: true
      reload:
        commands:
          help: true
      downloadPlugins:
        commands:
          help: true
          plugins: true
          download: true
          logs: true
          downloadlog: true
  default:
    plugins:
      test:
        enable: true
        commands:
          help: true
          param: false
